//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingForAgriculturalTax {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IncomeTypeCodeData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IncomeTypeCodeData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountingForAgriculturalTax.IncomeTypeCodeData", typeof(IncomeTypeCodeData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Целевое финансирование в виде грантов.
        /// </summary>
        internal static string КодПоступлений_010 {
            get {
                return ResourceManager.GetString("КодПоступлений_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Целевое финансирование в виде инвестиций, полученных при проведении инвестиционных  конкурсов (торгов) в порядке, установленном законодательством Российской Федерации.
        /// </summary>
        internal static string КодПоступлений_020 {
            get {
                return ResourceManager.GetString("КодПоступлений_020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Целевое финансирование в виде инвестиций, полученных от иностранных инвесторов на финансирование капитальных вложений производственного назначения, при условии использования их в течение одного календарного года с момента получения.
        /// </summary>
        internal static string КодПоступлений_030 {
            get {
                return ResourceManager.GetString("КодПоступлений_030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Взносы учредителей (участников, членов)..
        /// </summary>
        internal static string КодПоступлений_120 {
            get {
                return ResourceManager.GetString("КодПоступлений_120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доходы в виде безвозмездно полученных некоммерческими организациями работ (услуг), выполненных (оказанных) на основании соответствующих договоров.
        /// </summary>
        internal static string КодПоступлений_130 {
            get {
                return ResourceManager.GetString("КодПоступлений_130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожертвования, признаваемые таковыми в соответствии с  гражданским законодательством Российской Федерации.
        /// </summary>
        internal static string КодПоступлений_140 {
            get {
                return ResourceManager.GetString("КодПоступлений_140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчисления на формирование в установленном статьей 324 Налогового кодекса Российской Федерации (далее – Кодекс) порядке резерва на проведение ремонта, капитального ремонта общего имущества, которые производятся садоводческому, садово-огородному кооперативу или иному специализированному потребительскому кооперативу их членами.
        /// </summary>
        internal static string КодПоступлений_141 {
            get {
                return ResourceManager.GetString("КодПоступлений_141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имущество, имущественные права, переходящие некоммерческим организациям по завещанию в порядке наследования.
        /// </summary>
        internal static string КодПоступлений_160 {
            get {
                return ResourceManager.GetString("КодПоступлений_160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средства, предоставленные на осуществление уставной деятельности некоммерческих организаций из федерального бюджета
        ///.
        /// </summary>
        internal static string КодПоступлений_170 {
            get {
                return ResourceManager.GetString("КодПоступлений_170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средства, предоставленные на осуществление уставной деятельности некоммерческих организаций из бюджетов субъектов Российской Федерации.
        /// </summary>
        internal static string КодПоступлений_171 {
            get {
                return ResourceManager.GetString("КодПоступлений_171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средства, предоставленные на осуществление уставной деятельности некоммерческих организаций из местных бюджетов.
        /// </summary>
        internal static string КодПоступлений_172 {
            get {
                return ResourceManager.GetString("КодПоступлений_172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средства, предоставленные на осуществление уставной деятельности некоммерческих организаций из бюджетов  государственных внебюджетных фондов.
        /// </summary>
        internal static string КодПоступлений_173 {
            get {
                return ResourceManager.GetString("КодПоступлений_173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средства и иное имущество, имущественные права, полученные на осуществление  благотворительной деятельности.
        /// </summary>
        internal static string КодПоступлений_180 {
            get {
                return ResourceManager.GetString("КодПоступлений_180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поступления от собственников созданным ими учреждениям.
        /// </summary>
        internal static string КодПоступлений_220 {
            get {
                return ResourceManager.GetString("КодПоступлений_220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средства, полученные некоммерческими организациями безвозмездно на обеспечение ведения уставной деятельности, не связанной с предпринимательской деятельностью, от созданных ими в соответствии с законодательством Российской Федерации структурных подразделений (отделений), являющихся налогоплательщиками (далее - структурные подразделения (отделения)), перечисленные структурными подразделениями (отделениями) за счет целевых поступлений, поступивших им на содержание и ведение уставной деятельности.
        /// </summary>
        internal static string КодПоступлений_281 {
            get {
                return ResourceManager.GetString("КодПоступлений_281", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средства, полученные структурными подразделениями (отделениями) от создавших их в соответствии с законодательством Российской Федерации некоммерческих организаций, перечисленные некоммерческими организациями за счет целевых поступлений, полученных ими на содержание и ведение уставной деятельности.
        /// </summary>
        internal static string КодПоступлений_282 {
            get {
                return ResourceManager.GetString("КодПоступлений_282", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Денежные средства, недвижимое имущество, ценные бумаги, полученные некоммерческими организациями на формирование или пополнение целевого капитала, которые осуществляются в порядке, установленном Федеральным законом от 30 декабря 2006 г. № 275-ФЗ «О порядке формирования и использования целевого капитала некоммерческих организаций» (Собрание законодательства Российской Федерации, 2007, № 1, ст. 38;  2009, № 48, ст. 5731; 2011, № 48, ст.6728, ст.6729; 2012, № 31, ст. 4323; 2013, № 30, ст. 4084) (далее - Федера [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string КодПоступлений_321 {
            get {
                return ResourceManager.GetString("КодПоступлений_321", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Денежные средства, полученные некоммерческими организациями - собственниками целевого капитала от  управляющих компаний, осуществляющих доверительное управление имуществом, составляющим целевой капитал, в соответствии с Федеральным законом «О порядке формирования и использования  целевого капитала некоммерческих организаций».
        /// </summary>
        internal static string КодПоступлений_322 {
            get {
                return ResourceManager.GetString("КодПоступлений_322", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Денежные средства, полученные некоммерческими организациями от специализированных организаций управления  целевым капиталом в соответствии с Федеральным законом «О  порядке формирования и использования целевого капитала  некоммерческих организаций».
        /// </summary>
        internal static string КодПоступлений_323 {
            get {
                return ResourceManager.GetString("КодПоступлений_323", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имущественные права в виде  права безвозмездного пользования государственным и муниципальным имуществом, полученные по решениям органов государственной власти и органов местного самоуправления некоммерческими организациями на ведение ими уставной деятельности.
        /// </summary>
        internal static string КодПоступлений_324 {
            get {
                return ResourceManager.GetString("КодПоступлений_324", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средства и иное имущество, полученные в виде безвозмездной помощи (содействия) в порядке, установленном   Федеральным законом от 4 мая 1999 г. № 95-ФЗ «О безвозмездной помощи (содействии) Российской Федерации и внесении изменений и дополнений в отдельные законодательные акты Российской Федерации о налогах и об установлении льгот по платежам в    государственные внебюджетные фонды в связи с осуществлением  безвозмездной помощи (содействия) Российской Федерации» (Собрание законодательства Российской Федерации [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string КодПоступлений_340 {
            get {
                return ResourceManager.GetString("КодПоступлений_340", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имущество, полученное государственными и муниципальными учреждениями по решению органов исполнительной власти        
        ///.
        /// </summary>
        internal static string КодПоступлений_360 {
            get {
                return ResourceManager.GetString("КодПоступлений_360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средства и иное имущество, полученные унитарными предприятиями от собственника имущества этого предприятия или  уполномоченного им органа.
        /// </summary>
        internal static string КодПоступлений_400 {
            get {
                return ResourceManager.GetString("КодПоступлений_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Иные полученные целевые средства, не учитываемые при определении налоговой базы в соответствии со статьей 251 Кодекса.
        /// </summary>
        internal static string КодПуступлений_500 {
            get {
                return ResourceManager.GetString("КодПуступлений_500", resourceCulture);
            }
        }
    }
}
