//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingForAgriculturalTax {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HelpInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountingForAgriculturalTax.HelpInfo", typeof(HelpInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При представлении в налоговый орган первичной Декларации по реквизиту «номер корректировки» проставляется «0--», при представлении уточненной Декларации - указывается номер корректировки (например, «1--», «2--» и так далее)..
        /// </summary>
        internal static string ЕСХН_ТИТУЛ_НомерКорректировки {
            get {
                return ResourceManager.GetString("ЕСХН_ТИТУЛ_НомерКорректировки", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При представлении в налоговый орган по месту учета организацией-правопреемником Декларации за последний налоговый период и уточненных Деклараций за реорганизованную организацию (в форме присоединения к другому юридическому лицу, слияния нескольких юридических лиц, разделения юридического лица, преобразования одного юридического лица в другое) в Титульном листе по реквизиту «по месту учета» указывается код «215» или «216»..
        /// </summary>
        internal static string ЕСХН_ТИТУЛ_ПредставляетсяВНалоговыйОрган {
            get {
                return ResourceManager.GetString("ЕСХН_ТИТУЛ_ПредставляетсяВНалоговыйОрган", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В поле «ИНН реорганизованной организации» указывается, ИНН который был присвоен организации до реорганизации налоговым органом по месту ее нахождения  (по налогоплательщикам, отнесенным к категории крупнейших, - налоговым органом по месту учета в качестве крупнейшего налогоплательщика)..
        /// </summary>
        internal static string ЕСХН_ТИТУЛ_РеорганизованныйИНН {
            get {
                return ResourceManager.GetString("ЕСХН_ТИТУЛ_РеорганизованныйИНН", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В поле «КПП реорганизованной организации» указывается, КПП который был присвоен организации до реорганизации налоговым органом по месту ее нахождения  (по налогоплательщикам, отнесенным к категории крупнейших, - налоговым органом по месту учета в качестве крупнейшего налогоплательщика)..
        /// </summary>
        internal static string ЕСХН_ТИТУЛ_РеорганизованныйКПП {
            get {
                return ResourceManager.GetString("ЕСХН_ТИТУЛ_РеорганизованныйКПП", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реорганизация компаний представляет собой прекращение юридического лица с переходом прав и обязанностей. При реорганизации компаний деятельность подвергшегося реорганизации юридического лица продолжают другие лица. 
        ///Исходя из положений статьи 57 и 58 ГК, различает пять видов реорганизации: слияние (два и более юридических лиц превращаются в одно), присоединение (одно или несколько юридических лиц присоединяются к другому), разделение (юридическое лицо делится на два или более юридических лиц), выделение (и [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ЕСХН_ТИТУЛ_ФормаРеорганизации {
            get {
                return ResourceManager.GetString("ЕСХН_ТИТУЛ_ФормаРеорганизации", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В данном поле указывается код по ОКТМО муниципального образования, межселенной территории, населенного пункта, входящего в состав муниципального образования по месту нахождения организации (по месту жительства индивидуального предпринимателя). 
        ///Данное поле указываются только при смене места нахождения организации (места жительства индивидуального предпринимателя)..
        /// </summary>
        internal static string ЕСХН_Ч2_ВторойКодПоОКТМО {
            get {
                return ResourceManager.GetString("ЕСХН_Ч2_ВторойКодПоОКТМО", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В данном поле указывается код по ОКТМО муниципального образования, межселенной территории, населенного пункта, входящего в состав муниципального образования по месту нахождения организации (по месту жительства индивидуального предпринимателя). 
        ///Данное поле указывается в обязательном порядке..
        /// </summary>
        internal static string ЕСХН_Ч2_ПервыйКодПоОКТМО {
            get {
                return ResourceManager.GetString("ЕСХН_Ч2_ПервыйКодПоОКТМО", resourceCulture);
            }
        }
    }
}
